export const COUNTER_INCREMENT ="COUNTER_INCREMENT"

export const COUNTER_DECREMENT ="COUNTER_DECREMENT"

export const COUNTER_INCBYX="COUNTER_INCBYX"

export const COUNTER_DECBYX="COUNTER_DECBYX"

export const COUNTER_MULTIBYX="COUNTER_MULTIBYX"

export const COUNTER_DIVIDEBYX="COUNTER_DIVIDEBYX"